# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
jobs:
  - job: WindowsTest
    displayName: "Testing on Windows VM"
    pool:
     name: default

    steps:
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            # Write your PowerShell commands here.
            
            Write-Host "Start Windows Test"
            Start-Sleep -Seconds 120
            Write-Host "Stop Windows Test"

  - job: LinuxTest
    displayName: "Testing on Linux VM"
    pool:
     name: default

    steps:
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            # Write your PowerShell commands here.
            
            Write-Host "Start Linux Test"
            Start-Sleep -Seconds 120
            Write-Host "Stop Windows Test"