# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  none

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'MVCTraining/MVCTraining.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Build
  jobs:
  - job: Build
    displayName: 'Build and Publish'
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '5.x'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '$(solution)'
        arguments: '--Configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true
      displayName: 'Publish the .NET Core MVC application'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'drop'
        publishLocation: 'pipeline'

- stage: Deploy
  jobs:
  - job: Deploy
    displayName: 'Deploy to Azure Web App'
    steps:
  
    - download: current
      artifact: 'drop'
      

    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'Free Trial(03111732-4a2b-4276-9b78-32e49c83ac59)'
        appType: 'webApp'
        appName: 'MVCTrainWebapp'
        package: '$(System.ArtifactsDirectory)/**/*.zip'
        deploymentMethod: 'auto'
