# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  none
#  paths:
#    include: 
#     - MVCTraining/*
#  branches:
#   include:
#     - main



pool:
  vmImage: 'windows-latest'

variables:
  solution: 'MVCTraining/MVCTraining.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  outputDirectory: 'PublishOut'
  project: 'MVCTraining/MVCTraining.csproj'

stages: 
- stage: Build
  jobs:
  - job: Build
    displayName: 'Build Job'
    steps:
    - task: UseDotNet@2

      inputs:
        packageType: 'sdk'
        version: '5.x'
        
    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        restoreSolution: '$(solution)'
        feedsToUse: 'select'


    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '$(solution)'

        arguments: '--output $(outputDirectory)'
    

  - job: Publish
    displayName: 'Publish Job'
    dependsOn: Build

    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '5.x'

    - script: dotnet publish $(solution) --output $(outputDirectory)/published --configuration $(buildConfiguration)
      displayName: 'Publish .NET Application'
    
    
    - task: NuGetCommand@2
      inputs: 
          command: 'pack'
          packagesToPack: '$(project)'
          configuration: '$(buildConfiguration)'
          packDestination: '$(outputDirectory)'
          versioningScheme: 'off'
      
    - task: NuGetCommand@2
      inputs:
        command: 'push'
        packagesToPush: '$(outputDirectory)/**/*.nupkg;!$(outputDirectory)/**/*.symbols.nupkg'
        nuGetFeedType: 'internal'
        publishVstsFeed: '89c8f2c4-5987-4092-848b-a5db4f97daa5/6d27ffef-1008-434f-a180-008f1337df6f'
        allowPackageConflicts: true
#    - task: PublishPipelineArtifact@1
#      inputs:
#        targetPath: '*.nupkg'
#        artifact: 'test'
#        publishLocation: 'pipeline'